### ISSUE TITLE
Samsung Galaxy S

### ISSUE THREAD

**Issue by sudoxd** [sudoxd/xyz.sudoxd.phone#1]
**What phone do you want added**
Samsung Galaxy S

**If Possible, Please link me the Manufacturer and GSMArena links to the requested phones**
(Manufacturer Link)
https://www.gsmarena.com/samsung_i9000_galaxy_s-3115.php

**If Possible, Please link me the most common roms for this phone on XDA-Developers**
(XDA Rom Links)

**Additional context**
Any other information about the requested device should go here

**Comment by prometheus1337** [comment]
https://forum.xda-developers.com/showthread.php?t=886000
