### ISSUE TITLE
Moto G5+

### ISSUE THREAD

**Issue by jared704** [sudoxd/xyz.sudoxd.phone#9]
**What phone do you want added**
Moto G5+
**If Possible, Please link me the Manufacturer and GSMArena links to the requested phones**
Manufacturer Link: https://www.motorola.com/us/products/moto-g-plus
GSMarena: https://www.gsmarena.com/motorola_moto_g5_plus-8453.php

**If Possible, Please link me the most common roms for this phone on XDA-Developers**
https://forum.xda-developers.com/g5-plus/development/rom-pie-9-x-arrowos-9-x-t3838052
https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3880088
https://forum.xda-developers.com/g5-plus/development/9-0-resurrection-remix-v7-0-t3891128
https://forum.xda-developers.com/g5-plus/development/rom-android-source-illusion-project-t3873179

**Is the device treble supported? if unofficially please link the tutorials below (preferably from xda)**
Yes unofficial
*Flashing Vache and Gtrcraft's custom TWRP: https://forum.xda-developers.com/g5-plus/development/dev-project-treble-potter-t3801292

**Additional context**
**Any other information about the requested device should go here**
The camera when on a custom rom breaks proper 60fps recording. To fix this you must flash a systemless camera using Magisk. You can also flash Resurrection Remix to get proper 60FPS recording support.

If you flash stock with fastboot you WILL loose your entire EFS partition that holds your imei to make calls. The only way to prevent you from losing your imei is backing up the EFS and persist partition by flashing Gtrcraft's custom Persist TWRP.

**Comment by sudoxd** [comment]
Finished in v1.3.4
